### ISSUE TITLE
Removes containers that were never started?

### ISSUE THREAD

**Issue by tedyoung** [spotify/docker-gc#13]
I haven't yet tried it out (cuz the install required doing stuff on my machine that I don't yet want to do...), but it looks like containers that were created (e.g., via `docker create busybox`), but not started, will be garbage-collected because the "FinishedAt" timestamp is "0001-01-01T00:00:00Z", which is certainly more than an hour ago.

Am I misreading the code here?

**Comment by rohansingh** [comment]
Yup, I believe that's a correct reading. I think it's something we never considered since we don't really create containers and leave them around for a while without starting them.

Though if you get unlucky with timing, I guess this could happen in the time between when you create a container and start it even if you plan on starting it immediately.

**Comment by MrMMorris** [comment]
this relates to https://github.com/spotify/docker-gc/issues/23. Let me know if I should delete my issue and keep the discussion here.

**Comment by dnephin** [comment]
If this is a critical issue for anyone, you might be interested in https://github.com/Yelp/docker-custodian (disclaimer: I'm the primary contributor), which has basically identical functionality to docker-gc (except that it's python not bash, has unit tests, and uses the api instead of the cli).

It handles this issue properly:
https://github.com/Yelp/docker-custodian/blob/v0.4.0/docker_custodian/docker_gc.py#L49

**Comment by MrMMorris** [comment]
@dnephin that's amazing, thanks!

Does it leave Data Only containers alone by default?

**Comment by dnephin** [comment]
It does not. I'll open an issue for that feature (I believe it may be the only one missing).

**Comment by mattnworb** [comment]
> Though if you get unlucky with timing, I guess this could happen in the time between when you create a container and start it even if you plan on starting it immediately.

I think the addition of GRACE_PERIOD_SECONDS would remove this unlucky timing condition.

I am going to close this for now as I don't think there is a huge need to remove containers that were never started now that GRACE_PERIOD_SECONDS fixes the timing issue and the support for excluding certain container IDs exists.
