### ISSUE TITLE
docker rmi will fail if image has multiple repo:tag references

### ISSUE THREAD

**Issue by HardySimpson** [spotify/docker-gc#15]
Learn many from docker-gc. I didn't run docker-gc but read the code.

the docker-gc's way of remove a image is
```
docker rmi $(image_id)
```
if the image has multiple repo:tag reference to it, the command will fail. 
my shell removes repo:tag instead of imageid mostly,  avoid the bug.

**Comment by jaakkytt** [comment]
Also stumbled upon of this after seeing my image in images.reap not being deleted. 
Ran the last line of the docker-gc file again:

    $ xargs -n 1 docker rmi < images.reap 
    Error response from daemon: Conflict, cannot delete image e33b075d9148c4ef66be11e7faa1d1a46144e10427fdb81406fff97270f61ca2 because it is tagged in multiple repositories, use -f to force
    Error: failed to remove images: [e33b075d9148c4ef66be11e7faa1d1a46144e10427fdb81406fff97270f61ca2]

**Comment by dnephin** [comment]
If this is a critical issue for anyone, you might be interested in https://github.com/Yelp/docker-custodian (disclaimer: I'm the primary contributor), which has basically identical functionality to docker-gc (except that it's python not bash, has unit tests, and uses the api instead of the cli).

It handles this issue:
https://github.com/Yelp/docker-custodian/blob/v0.4.0/docker_custodian/docker_gc.py#L119

**Comment by arnib** [comment]
This should be fixed in #72, enable by using ```FORCE_IMAGE_REMOVAL=1 docker-gc```
